### ISSUE TITLE
You are manually calling a React.PropTypes validation function for the `lang` prop on `Provider`

### ISSUE THREAD

**Issue by OpenGrid** [queicherius/react-globe#5]
This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by queicherius** [comment]
I just tried recreating that error, but I couldn't get it to show up (with react 15.3.0). Which versions are you using? Could you post the stacktrace / some source code to reproduce it?

**Comment by queicherius** [comment]
I'd still love to fix this. However, I still need more information. 😞
